//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelDataConvert.resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class stringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal stringResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExcelDataConvert.resources.stringResource", typeof(stringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Elija que numero de hoja desea convertir:  .
        /// </summary>
        internal static string stringNumberSheet {
            get {
                return ResourceManager.GetString("stringNumberSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Introduzca la ruta donde se guardara el archivo:  .
        /// </summary>
        internal static string stringPathCsv {
            get {
                return ResourceManager.GetString("stringPathCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Por favor introduzca la ruta del archivo excel:  .
        /// </summary>
        internal static string stringPathExcel {
            get {
                return ResourceManager.GetString("stringPathExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----------------------------------------------------------------------------------.
        /// </summary>
        internal static string stringSeparetor {
            get {
                return ResourceManager.GetString("stringSeparetor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *** Ruta donde se guardara archivo Csv:  .
        /// </summary>
        internal static string stringSummaryBodyCsv {
            get {
                return ResourceManager.GetString("stringSummaryBodyCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *** Ruta de documento Excel:  .
        /// </summary>
        internal static string stringSummaryBodyExcel {
            get {
                return ResourceManager.GetString("stringSummaryBodyExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *** Numero de sheet se convertira:  .
        /// </summary>
        internal static string stringSummaryBodySheet {
            get {
                return ResourceManager.GetString("stringSummaryBodySheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Desea convertir el archivo Excel con estas opciones? Si/No : .
        /// </summary>
        internal static string stringSummaryConfirmation {
            get {
                return ResourceManager.GetString("stringSummaryConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Resumen de las opciones ingresadas.
        /// </summary>
        internal static string stringSummaryHead {
            get {
                return ResourceManager.GetString("stringSummaryHead", resourceCulture);
            }
        }
    }
}
